# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqBeE-f7fSgq-nUGeV2hjFb-vTjm9lvx
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

# Load dataset
df = pd.read_csv("/content/Thyroid_Diff.csv.xls")

# Drop unnecessary columns if any
df = df.dropna()

# Target column (change if different)
target = "Recurred"

# Encode categorical columns
label_encoders = {}
for col in df.columns:
    if df[col].dtype == "object":
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le

# Split data
X = df.drop(target, axis=1)
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train model
model = RandomForestClassifier(n_estimators=200)
model.fit(X_train, y_train)

# Save files
joblib.dump(model, "thyroid_model.pkl")
joblib.dump(label_encoders, "encoders.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")

print("✅ Model trained and saved successfully!")

